[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
clap = "3.0.0-beta.5"
dotenv = "0.15.0"
itertools = "0.10.1"
seq-macro = "0.2.2"
ureq = "2.3.1"
zstd = "0.9.0"

[features]
